apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  namespace: roboshop
data:
  REDIS_HOST: "{{ .Values.config.REDIS_HOST }}"
  CATALOGUE_HOST: "{{ .Values.config.CATALOGUE_HOST }}"
  CATALOGUE_PORT: "{{ .Values.config.CATALOGUE_PORT }}"