apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: roboshop
spec:
  type: {{.values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .values.service.servicePort }}
      targetPort: {{ .values.service.containerPort }}